/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package one.way.anova.calculator;

/**
 *
 * @author hashi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_ssbetween = new javax.swing.JLabel();
        lbl_sswithin = new javax.swing.JLabel();
        lbl_sstotal = new javax.swing.JLabel();
        lbl_dofbetween = new javax.swing.JLabel();
        lbl_dofwithin = new javax.swing.JLabel();
        lbl_doftotal = new javax.swing.JLabel();
        lbl_mst = new javax.swing.JLabel();
        lbl_mse = new javax.swing.JLabel();
        lbl_fratio = new javax.swing.JLabel();
        lbl_fratio1 = new javax.swing.JLabel();
        lbl_mse2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_input = new javax.swing.JTextArea();
        btn_calculate = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        lbl_mse3 = new javax.swing.JLabel();
        lbl_mse4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("One Way ANOVA Calculator- created by -J0K3R-"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Source of<br> Variation<html>");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html>Sum of<br>Squares<html>");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html>Degrees of<br>Freedom<html>");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html>Mean<br>Squares<html>");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("<html>F<br>Ratio<html>");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html>Between<br>Treatments<html>");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<html>Within<br>Treatments<html>");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Total");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbl_ssbetween.setBackground(new java.awt.Color(153, 255, 0));
        lbl_ssbetween.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_ssbetween.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ssbetween.setText("00");
        lbl_ssbetween.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbl_sswithin.setBackground(new java.awt.Color(153, 255, 0));
        lbl_sswithin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_sswithin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sswithin.setText("00");
        lbl_sswithin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbl_sstotal.setBackground(new java.awt.Color(153, 255, 0));
        lbl_sstotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_sstotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sstotal.setText("00");
        lbl_sstotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbl_dofbetween.setBackground(new java.awt.Color(153, 255, 0));
        lbl_dofbetween.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_dofbetween.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dofbetween.setText("00");
        lbl_dofbetween.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbl_dofwithin.setBackground(new java.awt.Color(153, 255, 0));
        lbl_dofwithin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_dofwithin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dofwithin.setText("00");
        lbl_dofwithin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbl_doftotal.setBackground(new java.awt.Color(153, 255, 0));
        lbl_doftotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_doftotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_doftotal.setText("00");
        lbl_doftotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbl_mst.setBackground(new java.awt.Color(153, 255, 0));
        lbl_mst.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_mst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_mst.setText("00");
        lbl_mst.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbl_mse.setBackground(new java.awt.Color(153, 255, 0));
        lbl_mse.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_mse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_mse.setText("00");
        lbl_mse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbl_fratio.setBackground(new java.awt.Color(153, 255, 0));
        lbl_fratio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_fratio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_fratio.setText("00");
        lbl_fratio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbl_fratio1.setBackground(new java.awt.Color(153, 255, 0));
        lbl_fratio1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_fratio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_fratio1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbl_mse2.setBackground(new java.awt.Color(153, 255, 0));
        lbl_mse2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_mse2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_mse2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        txt_input.setColumns(20);
        txt_input.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txt_input.setRows(5);
        txt_input.setText("Enter the observations seperated by comma \nand Treatments(Groups) seperated by lines. \nOne line for one treatment(group).\ntype\"!\" at the end\n\nEx:-\n1,2,3,4,5,6\n1,2,3,4,5,6\n1,2,3,4,5,6!\n");
        txt_input.setToolTipText("<html>Enter the observations seperated by comma <br>\nand Treatments(Groups) seperated by lines.<br> \nOne line for one treatment(group)\n<br>\ntype\"!\" at the end.\n<br>\n\nEx:-<br>\n1,2,3,4,5,6<br>\n7,8,9,10,11,12<br>\n13,14,15,16,17,18!\n<html>\n");
        jScrollPane1.setViewportView(txt_input);

        btn_calculate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_calculate.setText("Calculate");
        btn_calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calculateActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_clear.setText("Clear All");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        lbl_mse3.setBackground(new java.awt.Color(153, 255, 0));
        lbl_mse3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_mse3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_mse3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lbl_mse4.setBackground(new java.awt.Color(153, 255, 0));
        lbl_mse4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_mse4.setForeground(new java.awt.Color(255, 51, 51));
        lbl_mse4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_mse4.setText("<html>Don't forget to<br>\nType \"!\" at the End<html>");
        lbl_mse4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_calculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_mse4, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(lbl_ssbetween, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_sswithin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_sstotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbl_dofwithin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_dofbetween, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(lbl_doftotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_mst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_mse3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_mse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(lbl_fratio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_fratio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_mse2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_calculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_mse4, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_fratio, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))
                            .addComponent(lbl_fratio1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_mse2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbl_mst, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(107, 107, 107)
                            .addComponent(lbl_mse3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_ssbetween, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_sswithin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_mse, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_sstotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_dofbetween, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))
                            .addComponent(lbl_dofwithin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_doftotal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txt_input.setText("");
        lbl_ssbetween.setText("-");
        lbl_sswithin.setText("-");
        lbl_sstotal.setText("-");
        lbl_dofbetween.setText("-");
        lbl_dofwithin.setText("-");
        lbl_doftotal.setText("-");
        lbl_mst.setText("-");
        lbl_mse.setText("-");
        lbl_fratio.setText("-");

    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calculateActionPerformed
        String input= txt_input.getText();
        //creating variables for number of replicants=n, number of treatments=a and number of observations = N
        int n=1;
        int a=1;
        int N=0;
        //counting replicants
        int i=0;
        while(input.charAt(i)!='\n'){
            if(input.charAt(i)==','){
                n=n+1;
            }
            i=i+1;
        }
        //counting treatments
        i=0;
        while(i<input.length()){
            if(input.charAt(i)=='\n'){
                a=a+1;
            }
            i=i+1;
        }
        //calculating number of observations =N
        N=a*n;
        // making 2d array and storing observation valuses in it
        String tempval="";
        double observations[][] = new double[a][n];
        i=0;
        int j=0;
        int k=0;
        while(i<input.length()-1){
            if(input.charAt(i)!=',' || input.charAt(i)!='\n'){
                tempval=tempval+input.charAt(i);
                i=i+1;
            }

            if(input.charAt(i)==','){
                observations[j][k]=Double.parseDouble(tempval);
                tempval="";
                k=k+1;
                i=i+1;
            }

            if(input.charAt(i)=='\n'){
                observations[j][k]=Double.parseDouble(tempval);
                tempval="";
                k=0;
                j=j+1;
                i=i+1;
            }

            if(i==input.length()-1){
                observations[j][k]=Double.parseDouble(tempval);
                tempval="";
                j=0;
                k=0;
                i=i+1;
            }

        }

        i=0;
        j=0;
        k=0;
        /* checking Boservations array
        for(i=0;i<a;i++){
            for(j=0;j<n;j++){
                System.out.println(observations[i][j]);
            }
            System.out.println("");
        }
        no errors were found */

        //calsulating Grand total and grand mean;
        double grandtotal=0;
        double grandmean=0;
        for(i=0;i<a;i++){
            for(j=0;j<n;j++){
                grandtotal = grandtotal+observations[i][j];
            }
        }
        grandmean=grandtotal/N;

        /* checking Grand total and grand mean
        System.out.println(grandtotal);
        System.out.println(grandmean);

        no errors were found */

        //calculating sstotal
        double sstotal=0;
        for(i=0;i<a;i++){
            for(j=0;j<n;j++){
                sstotal=sstotal +(observations[i][j]-grandmean)*(observations[i][j]-grandmean);
            }
        }

        //calculating and storing treatments' means in a array
        double treatmentmeans[]=new double[a];
        for(i=0;i<a;i++){
            treatmentmeans[i]=0;
        }
        for(i=0;i<a;i++){
            for(j=0;j<n;j++){
                treatmentmeans[i]=treatmentmeans[i]+observations[i][j];
            }
            treatmentmeans[i]=treatmentmeans[i]/n;
        }
        //calculating ssbetween
        double ssbetween=0;
        for(i=0;i<a;i++){
            ssbetween=ssbetween+(treatmentmeans[i]-grandmean)*(treatmentmeans[i]-grandmean);
        }
        ssbetween=ssbetween*n;

        //calculating sswithin
        double sswithin=sstotal-ssbetween;

        //calculating mst and mse
        double mst=ssbetween/(a-1);
        double mse=sswithin/(N-a);
        double Fratio=mst/mse;

        //updating outputtable
        lbl_ssbetween.setText(String.valueOf(ssbetween));
        lbl_sswithin.setText(String.valueOf(sswithin));
        lbl_sstotal.setText(String.valueOf(sstotal));
        lbl_dofbetween.setText(String.valueOf(a-1));
        lbl_dofwithin.setText(String.valueOf(N-a));
        lbl_doftotal.setText(String.valueOf(N-1));
        lbl_mst.setText(String.valueOf(mst));
        lbl_mse.setText(String.valueOf(mse));
        lbl_fratio.setText(String.valueOf(Fratio));

    }//GEN-LAST:event_btn_calculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calculate;
    private javax.swing.JButton btn_clear;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_dofbetween;
    private javax.swing.JLabel lbl_doftotal;
    private javax.swing.JLabel lbl_dofwithin;
    private javax.swing.JLabel lbl_fratio;
    private javax.swing.JLabel lbl_fratio1;
    private javax.swing.JLabel lbl_mse;
    private javax.swing.JLabel lbl_mse2;
    private javax.swing.JLabel lbl_mse3;
    private javax.swing.JLabel lbl_mse4;
    private javax.swing.JLabel lbl_mst;
    private javax.swing.JLabel lbl_ssbetween;
    private javax.swing.JLabel lbl_sstotal;
    private javax.swing.JLabel lbl_sswithin;
    private javax.swing.JTextArea txt_input;
    // End of variables declaration//GEN-END:variables
}
